version: '2'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    image: blankia/jenkins:1.2
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
        DOCKER_ENGINE: ${DOCKER_ENGINE}
        DOCKER_COMPOSE: ${DOCKER_COMPOSE}
    volumes:
      - jenkins_home:/var/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
